"""Add timezone to last_login_at

Revision ID: 9be7deac5364
Revises: 53cf65bfa5b4
Create Date: 2026-01-19 14:28:50.553684

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9be7deac5364"
down_revision: str | None = "53cf65bfa5b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("refresh_tokens_user_id_fkey"), "refresh_tokens", type_="foreignkey"
    )
    op.create_foreign_key(None, "refresh_tokens", "users", ["user_id"], ["id"])
    op.drop_constraint(
        op.f("role_permissions_permission_id_fkey"),
        "role_permissions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("role_permissions_role_id_fkey"), "role_permissions", type_="foreignkey"
    )
    op.create_foreign_key(None, "role_permissions", "roles", ["role_id"], ["id"])
    op.create_foreign_key(
        None, "role_permissions", "permissions", ["permission_id"], ["id"]
    )
    op.alter_column(
        "users",
        "last_login_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_constraint(op.f("users_role_id_fkey"), "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "roles", ["role_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_role_id_fkey"),
        "users",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.alter_column(
        "users",
        "last_login_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "role_permissions", type_="foreignkey")
    op.drop_constraint(None, "role_permissions", type_="foreignkey")
    op.create_foreign_key(
        op.f("role_permissions_role_id_fkey"),
        "role_permissions",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("role_permissions_permission_id_fkey"),
        "role_permissions",
        "permissions",
        ["permission_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "refresh_tokens", type_="foreignkey")
    op.create_foreign_key(
        op.f("refresh_tokens_user_id_fkey"),
        "refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
