"""add issue management tables

Revision ID: ccf68d53b6a5
Revises: a687fc7927a0
Create Date: 2026-01-29 17:38:15.888995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf68d53b6a5'
down_revision: Union[str, None] = 'a687fc7927a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('is_subtask', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Issue type definitions'
    )
    op.create_index('ix_issue_types_project_id', 'issue_types', ['project_id'], unique=False)
    op.create_table('labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_labels_project_name'),
    comment='Project labels for categorizing issues'
    )
    op.create_index('ix_labels_project_id', 'labels', ['project_id'], unique=False)
    op.create_table('statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('category', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='statuscategory'), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Issue status definitions'
    )
    op.create_index('ix_statuses_project_id', 'statuses', ['project_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'NONE', name='priority'), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['issue_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'issue_number', name='uq_issues_project_number'),
    comment='Issues for tracking work'
    )
    op.create_index('ix_issues_assignee_id', 'issues', ['assignee_id'], unique=False)
    op.create_index('ix_issues_deleted_at', 'issues', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_issues_key'), 'issues', ['key'], unique=True)
    op.create_index('ix_issues_parent_id', 'issues', ['parent_id'], unique=False)
    op.create_index('ix_issues_project_id', 'issues', ['project_id'], unique=False)
    op.create_index('ix_issues_status_id', 'issues', ['status_id'], unique=False)
    op.create_index('ix_issues_type_id', 'issues', ['type_id'], unique=False)
    op.create_table('issue_labels',
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id', 'label_id'),
    comment='Issue-label associations'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_labels')
    op.drop_index('ix_issues_type_id', table_name='issues')
    op.drop_index('ix_issues_status_id', table_name='issues')
    op.drop_index('ix_issues_project_id', table_name='issues')
    op.drop_index('ix_issues_parent_id', table_name='issues')
    op.drop_index(op.f('ix_issues_key'), table_name='issues')
    op.drop_index('ix_issues_deleted_at', table_name='issues')
    op.drop_index('ix_issues_assignee_id', table_name='issues')
    op.drop_table('issues')
    op.drop_index('ix_statuses_project_id', table_name='statuses')
    op.drop_table('statuses')
    op.drop_index('ix_labels_project_id', table_name='labels')
    op.drop_table('labels')
    op.drop_index('ix_issue_types_project_id', table_name='issue_types')
    op.drop_table('issue_types')
    # ### end Alembic commands ###
